# Use the official Node.js image as a base image
FROM node:14

# Set working directory
WORKDIR /var/www/html

# Install global dependencies
RUN npm install -g @vue/cli

# Copy existing application directory contents
COPY . /var/www/html

# Copy existing application directory permissions
COPY --chown=node:node . /var/www/html
